Database3
ArgTang/WebApplikasjonProject pull request #18
Opened 2016-10-12 12:28 UTC by oleespen

2016-10-14 12:20 UTC, ArgTang commented on src/GroupProject/Views/Home/Index.cshtml
> +﻿
denne må bort

2016-10-14 12:21 UTC, ArgTang commented on src/GroupProject/Migrations/PersonDbContextModelSnapshot.cs
> +
trenger ikke disse når vi har annotations i modellen

2016-10-14 12:24 UTC, ArgTang commented on src/GroupProject/Controllers/HomeController.cs
>      }
About og contact er slettet i master, trenger ikke legge de til

2016-10-14 12:25 UTC, ArgTang requested changes
se kommentarer

2016-10-14 15:04 UTC, ArgTang commented on src/GroupProject/Models/Person.cs
Kanskje bruke
[StringLength(11, MinimumLength=11)] istedet?

2016-10-17 07:50 UTC, oleespen commented on src/GroupProject/Migrations/PersonDbContextModelSnapshot.cs
> +
disse blir vel laget pga vi har annotations i modellen?

2016-10-17 07:51 UTC, oleespen commented on src/GroupProject/Controllers/HomeController.cs
>      }
ok

2016-10-17 07:51 UTC, oleespen commented on src/GroupProject/Views/Home/Index.cshtml
> +﻿
ok

2016-10-17 07:58 UTC, oleespen commented on src/GroupProject/Models/Person.cs
ok

2016-10-17 08:45 UTC, ArgTang approved these changes

2016-10-17 08:46 UTC, merged