Bankid 2.0
ArgTang/WebApplikasjonProject pull request #27
Opened 2016-10-18 19:42 UTC by aleksanderaleksic

2016-10-18 20:38 UTC, ArgTang requested changes

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Anotations/BirthNumber.cs
> +{
Annotaions med to enner

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Controllers/BankIdController.cs
> +        )
hvert argument på ny linje

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Controllers/BankIdController.cs
> +                            return View("Error");
forskjellig krøll brackets på else her og lenger nede

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Controllers/BankIdController.cs
> +                            return View("Error");
to elser med lik retur?

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Controllers/BankIdController.cs
> +        public IActionResult PostIdentify()
Antiforgery token, eller trengs det ikke her?

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Controllers/BankIdController.cs
> +        private readonly UserManager<ApplicationUser> _userManager;
private readonly strings?

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Views/BankId/Error.cshtml
> +                <div class="content error">
tom div?

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Views/BankId/Error.cshtml
> +                <div class="content error">
noen fler diver uten klasser nedover, brukes de til noe spesielt?

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Views/BankId/shared/_bankid.cshtml
>      </environment>
kan sette disse utenfor <environment> taggene hvis vi skal bruke samme på begge

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/wwwroot/bankid/js/identify.js
> +
Kan byttes med disse:
element.classList.Add/remove/toggle eller contains

https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/wwwroot/bankid/js/identify.js
> +    var request = $.ajax({
Bedre navn? postHva?

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/wwwroot/bankid/js/identify.js
> +        } else {
Funker dette? har satt LoggedinController til å ha Route Users

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/wwwroot/bankid/js/password.js
> +       }
showPassButton(passInput.value === ""); ?

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/wwwroot/bankid/js/password.js
> +       }
samme lengre ned, eller liker du at det ekplisitt er en if else sløyfe?

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/wwwroot/bankid/js/password.js
> +}
passInput.type = show ? "text":"password" ?

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/Views/BankId/Identify.cshtml
>  ﻿@{
Noen grunn til at vi ikke bruker ViewModels i disse? 

Jeg kan legge de til hvis du vil gjøre noe annet en stund

2016-10-18 20:38 UTC, ArgTang commented on src/GroupProject/wwwroot/bankid/js/identify.js
> +
classs med to sser

2016-10-18 20:39 UTC, ArgTang commented on src/GroupProject/Controllers/BankIdController.cs
> +        public IActionResult PostIdentify()
gjelder for httpPostene lenger ned også

2016-10-19 07:51 UTC, aleksanderaleksic commented on src/GroupProject/Controllers/BankIdController.cs
> +        public IActionResult PostIdentify()
Trengs vel egentlig bare hvis brukeren er autentisert

2016-10-19 08:01 UTC, aleksanderaleksic commented on src/GroupProject/Views/BankId/shared/_bankid.cshtml
>      </environment>
Hva tenker du på ?

2016-10-19 08:07 UTC, aleksanderaleksic commented on src/GroupProject/wwwroot/bankid/js/identify.js
> +    var request = $.ajax({
er jo en postrequest

2016-10-19 08:10 UTC, aleksanderaleksic commented on src/GroupProject/wwwroot/bankid/js/identify.js
> +        } else {
det fungerer, men om du ser en bedre løsning kom med forslag, prøve på andre ting i over 1 time uten at det funka.. Fungerte heller ikke å redirecte via .net

2016-10-19 08:11 UTC, aleksanderaleksic commented on src/GroupProject/wwwroot/bankid/js/password.js
> +       }
sjekker jo om passordet er tomt

2016-10-19 08:17 UTC, aleksanderaleksic commented on src/GroupProject/wwwroot/bankid/js/password.js
> +}
synes det er vanskeligere å lese

2016-10-19 08:18 UTC, aleksanderaleksic commented on src/GroupProject/Views/BankId/Identify.cshtml
>  ﻿@{
Ingen vits med viewmodels hvis man ikke bruker dem. Validering skjer på klient og server. Viewmodels ble vanskelig med ajax

2016-10-19 08:41 UTC, aleksanderaleksic commented on src/GroupProject/Views/BankId/Identify.cshtml
>  ﻿@{
tror jeg da..

2016-10-19 09:53 UTC, ArgTang commented on src/GroupProject/Controllers/BankIdController.cs
> +        public IActionResult PostIdentify()
nei den trengs alltid, er det for å hindre hacking

2016-10-19 09:54 UTC, ArgTang commented on src/GroupProject/wwwroot/bankid/js/password.js
> +}
ok

2016-10-19 09:55 UTC, ArgTang commented on src/GroupProject/wwwroot/bankid/js/password.js
> +       }
Ser det, men en kan slippe if else løkke hvis en sender med sjekken direkte

2016-10-19 09:56 UTC, ArgTang commented on src/GroupProject/Views/BankId/shared/_bankid.cshtml
>      </environment>
når linkene er like for alle enviroments kan vi likegodt sette de direkte inn i filen

2016-10-19 10:18 UTC, ArgTang commented on src/GroupProject/Views/BankId/Identify.cshtml
>  ﻿@{
viewmodels er passive, men de gjør validation og labels automatisk både på klient og server

2016-10-19 10:18 UTC, ArgTang commented on src/GroupProject/Views/BankId/Identify.cshtml
>  ﻿@{
jeg kan se på det

2016-10-20 10:55 UTC, ArgTang approved these changes

2016-10-20 10:57 UTC, merged