Enum
ArgTang/WebApplikasjonProject pull request #94
Opened 2016-11-03 12:01 UTC by oleespen

Fikset enumtype for kontotype

2016-11-03 14:19 UTC, ArgTang requested changes

2016-11-03 14:19 UTC, ArgTang commented on src/GroupProject/DAL/Models/Konto.cs
> +        public enum kontoNavn
Slett utkommentert kode

2016-11-04 08:45 UTC, oleespen commented on src/GroupProject/DAL/Models/Konto.cs
> +        public enum kontoNavn
fikset

2016-11-04 10:23 UTC, ArgTang approved these changes

2016-11-04 10:24 UTC, merged